import { HexChess } from '../src/hexchess'

test('load deafult', () => {
  const result = new HexChess()
  expect(result.board()).toEqual({
    f11: { color: 'b', type: 'b' },
    e10: { color: 'b', type: 'q' },
    g10: { color: 'b', type: 'k' },
    d9: { color: 'b', type: 'n' },
    f10: { color: 'b', type: 'b' },
    h9: { color: 'b', type: 'n' },
    c8: { color: 'b', type: 'r' },
    e9: null,
    g9: null,
    i8: { color: 'b', type: 'r' },
    b7: { color: 'b', type: 'p' },
    d8: null,
    f9: { color: 'b', type: 'b' },
    h8: null,
    j7: { color: 'b', type: 'p' },
    a6: null,
    c7: { color: 'b', type: 'p' },
    e8: null,
    g8: null,
    i7: { color: 'b', type: 'p' },
    k6: null,
    b6: null,
    d7: { color: 'b', type: 'p' },
    f8: null,
    h7: { color: 'b', type: 'p' },
    j6: null,
    a5: null,
    c6: null,
    e7: { color: 'b', type: 'p' },
    g7: { color: 'b', type: 'p' },
    i6: null,
    k5: null,
    b5: null,
    d6: null,
    f7: { color: 'b', type: 'p' },
    h6: null,
    j5: null,
    a4: null,
    c5: null,
    e6: null,
    g6: null,
    i5: null,
    k4: null,
    b4: null,
    d5: null,
    f6: null,
    h5: null,
    j4: null,
    a3: null,
    c4: null,
    e5: null,
    g5: null,
    i4: null,
    k3: null,
    b3: null,
    d4: null,
    f5: { color: 'w', type: 'p' },
    h4: null,
    j3: null,
    a2: null,
    c3: null,
    e4: { color: 'w', type: 'p' },
    g4: { color: 'w', type: 'p' },
    i3: null,
    k2: null,
    b2: null,
    d3: { color: 'w', type: 'p' },
    f4: null,
    h3: { color: 'w', type: 'p' },
    j2: null,
    a1: null,
    c2: { color: 'w', type: 'p' },
    e3: null,
    g3: null,
    i2: { color: 'w', type: 'p' },
    k1: null,
    b1: { color: 'w', type: 'p' },
    d2: null,
    f3: { color: 'w', type: 'b' },
    h2: null,
    j1: { color: 'w', type: 'p' },
    c1: { color: 'w', type: 'r' },
    e2: null,
    g2: null,
    i1: { color: 'w', type: 'r' },
    d1: { color: 'w', type: 'n' },
    f2: { color: 'w', type: 'b' },
    h1: { color: 'w', type: 'n' },
    e1: { color: 'w', type: 'q' },
    g1: { color: 'w', type: 'k' },
    f1: { color: 'w', type: 'b' },
  })
})
